# Generated by Django 5.2 on 2025-04-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessclassimage",
            name="fitness_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="classes.fitnessclass",
            ),
        ),
    ]
