# Generated by Django 5.2 on 2025-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
