# Generated by Django 5.2 on 2025-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
